// Package authproof implements the @bsv/auth proof scheme this service authenticates with.
//
// A proof is a signature over the canonical bytes "action\nidentityKey\nexpiresAt\nnonce",
// created with the BRC-42/43 key derived from protocol [2, "backup cache auth"], keyID =
// nonce and counterparty = the other side's identity key. It must stay byte-compatible
// with the published @bsv/auth TypeScript package (serializeAuthSigData + createAuthProof);
// testdata/vectors.json is generated by that package and pins the compatibility.
//
// Streaming is why the body is not signed directly: the action string carries the body's
// sha256 instead, so the server authenticates the sender from headers alone, then hashes
// the body as it streams to storage and compares at the end. A tampered body fails after
// upload, but it fails inside an open transaction and nothing is kept.
package authproof

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	ec "github.com/bsv-blockchain/go-sdk/primitives/ec"
	"github.com/bsv-blockchain/go-sdk/wallet"
)

// ProtocolName is the BRC-43 protocol both sides derive signing keys under.
// The TypeScript client passes it as [2, "backup cache auth"].
const ProtocolName = "backup cache auth"

// Header carries the proof. Its value is base64(JSON-encoded Proof).
const Header = "X-Bsv-Auth"

// Window is how long a proof stays valid; Skew is the tolerated clock difference.
// Both match the @bsv/auth defaults.
const (
	Window = 2 * time.Minute
	Skew   = 30 * time.Second
)

var (
	// ErrMalformed covers a proof that cannot be decoded or fails shape checks.
	ErrMalformed = errors.New("malformed auth proof")
	// ErrExpired means the proof's validity window has passed.
	ErrExpired = errors.New("auth proof expired")
	// ErrTooFarFuture means expiresAt exceeds now + window + skew — a fabricated expiry.
	ErrTooFarFuture = errors.New("auth proof expiry too far in the future")
	// ErrActionMismatch means the signed action does not describe this request.
	ErrActionMismatch = errors.New("auth proof action mismatch")
	// ErrBadSignature means the signature does not verify for the claimed identity.
	ErrBadSignature = errors.New("auth proof signature invalid")
)

// Proof is the wire shape carried in the Header, verbatim from the TypeScript client:
// the four signed fields plus the DER signature in base64.
type Proof struct {
	Action      string `json:"action"`
	IdentityKey string `json:"identityKey"`
	ExpiresAt   int64  `json:"expiresAt"` // Unix milliseconds, matching JS Date.now()
	Nonce       string `json:"nonce"`
	Signature   string `json:"signature"`
}

// Action builds the canonical action string for a request. requestURI is the literal
// path-plus-query as sent on the wire — no re-encoding, no sorting — so both sides agree
// without a canonicalization pass. bodySha256 is the lowercase hex digest of the request
// body, or "" for a bodyless request.
func Action(method, requestURI, bodySha256 string) string {
	if bodySha256 == "" {
		return method + " " + requestURI
	}
	return method + " " + requestURI + " sha256=" + bodySha256
}

// BodySha256 extracts the body digest an upload action claims, or "" for bodyless shapes.
func BodySha256(action string) string {
	i := strings.LastIndex(action, " sha256=")
	if i < 0 {
		return ""
	}
	return action[i+len(" sha256="):]
}

// Canonical is the byte sequence that gets signed: the four fields joined by '\n',
// exactly @bsv/auth's serializeAuthSigData.
func Canonical(action, identityKey string, expiresAt int64, nonce string) []byte {
	return []byte(strings.Join([]string{
		action, identityKey, strconv.FormatInt(expiresAt, 10), nonce,
	}, "\n"))
}

// Encode renders a proof as the Header value.
func Encode(p Proof) (string, error) {
	raw, err := json.Marshal(p)
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(raw), nil
}

// Decode parses a Header value.
func Decode(headerValue string) (Proof, error) {
	raw, err := base64.StdEncoding.DecodeString(headerValue)
	if err != nil {
		return Proof{}, fmt.Errorf("%w: %s", ErrMalformed, "header is not base64")
	}
	var p Proof
	if err := json.Unmarshal(raw, &p); err != nil {
		return Proof{}, fmt.Errorf("%w: %s", ErrMalformed, "header is not a JSON proof")
	}
	if p.Action == "" || p.IdentityKey == "" || p.Nonce == "" || p.Signature == "" {
		return Proof{}, fmt.Errorf("%w: %s", ErrMalformed, "missing fields")
	}
	return p, nil
}

// Sign builds a proof authorizing action, toward the verifier identified by
// counterpartyKey (compressed DER hex). Used by the Go client and by tests; the server
// only ever verifies.
func Sign(ctx context.Context, w wallet.Interface, counterpartyKey, action string, now time.Time) (Proof, error) {
	counterparty, err := ec.PublicKeyFromString(counterpartyKey)
	if err != nil {
		return Proof{}, fmt.Errorf("parse counterparty key: %w", err)
	}
	pub, err := w.GetPublicKey(ctx, wallet.GetPublicKeyArgs{IdentityKey: true}, "")
	if err != nil {
		return Proof{}, fmt.Errorf("read identity key: %w", err)
	}

	nonceBytes := make([]byte, 32)
	if _, err := rand.Read(nonceBytes); err != nil {
		return Proof{}, fmt.Errorf("draw nonce: %w", err)
	}
	p := Proof{
		Action:      action,
		IdentityKey: pub.PublicKey.ToDERHex(),
		ExpiresAt:   now.Add(Window).UnixMilli(),
		Nonce:       base64.StdEncoding.EncodeToString(nonceBytes),
	}

	sig, err := w.CreateSignature(ctx, wallet.CreateSignatureArgs{
		EncryptionArgs: wallet.EncryptionArgs{
			ProtocolID:   wallet.Protocol{SecurityLevel: wallet.SecurityLevelEveryAppAndCounterparty, Protocol: ProtocolName},
			KeyID:        p.Nonce,
			Counterparty: wallet.Counterparty{Type: wallet.CounterpartyTypeOther, Counterparty: counterparty},
		},
		Data: Canonical(p.Action, p.IdentityKey, p.ExpiresAt, p.Nonce),
	}, "")
	if err != nil {
		return Proof{}, fmt.Errorf("sign proof: %w", err)
	}
	der, err := sig.Signature.ToDER()
	if err != nil {
		return Proof{}, fmt.Errorf("encode signature: %w", err)
	}
	p.Signature = base64.StdEncoding.EncodeToString(der)
	return p, nil
}

// Verify checks shape, action, freshness and signature. It does NOT consume the nonce —
// single-use enforcement is the caller's, because it needs a store.
//
// On success it returns the authenticated identity key. The check order mirrors
// @bsv/auth's verifyAuthProof so both implementations refuse the same proofs for the
// same reasons.
func Verify(ctx context.Context, w wallet.Interface, p Proof, expectedAction string, now time.Time) (*ec.PublicKey, error) {
	if p.Action != expectedAction {
		return nil, ErrActionMismatch
	}
	nowMs := now.UnixMilli()
	if nowMs >= p.ExpiresAt {
		return nil, ErrExpired
	}
	if p.ExpiresAt-nowMs > (Window + Skew).Milliseconds() {
		return nil, ErrTooFarFuture
	}

	identity, err := ec.PublicKeyFromString(p.IdentityKey)
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrMalformed, "identity key is not a public key")
	}
	der, err := base64.StdEncoding.DecodeString(p.Signature)
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrMalformed, "signature is not base64")
	}
	sig, err := ec.ParseDERSignature(der)
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrMalformed, "signature is not DER")
	}

	res, err := w.VerifySignature(ctx, wallet.VerifySignatureArgs{
		EncryptionArgs: wallet.EncryptionArgs{
			ProtocolID:   wallet.Protocol{SecurityLevel: wallet.SecurityLevelEveryAppAndCounterparty, Protocol: ProtocolName},
			KeyID:        p.Nonce,
			Counterparty: wallet.Counterparty{Type: wallet.CounterpartyTypeOther, Counterparty: identity},
		},
		Data:      Canonical(p.Action, p.IdentityKey, p.ExpiresAt, p.Nonce),
		Signature: sig,
	}, "")
	if err != nil || !res.Valid {
		return nil, ErrBadSignature
	}
	return identity, nil
}
