package authproof_test

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"os"
	"strings"
	"testing"
	"time"

	ec "github.com/bsv-blockchain/go-sdk/primitives/ec"
	sdkwallet "github.com/bsv-blockchain/go-sdk/wallet"

	"github.com/bsv-blockchain/go-private-backup-cache/internal/authproof"
)

// vectors.json is generated by the published @bsv/auth TypeScript package
// (scratch script kept in test-client/genvectors.mjs). These tests are the
// cross-language compatibility pin: if they fail, Go and TS no longer agree
// on the signed bytes or the key derivation.
type vectorFile struct {
	ClientPrivHex     string `json:"clientPrivHex"`
	ServerPrivHex     string `json:"serverPrivHex"`
	ClientIdentityKey string `json:"clientIdentityKey"`
	ServerIdentityKey string `json:"serverIdentityKey"`
	Cases             []struct {
		Name            string `json:"name"`
		Action          string `json:"action"`
		IdentityKey     string `json:"identityKey"`
		ExpiresAt       int64  `json:"expiresAt"`
		Nonce           string `json:"nonce"`
		CanonicalHex    string `json:"canonicalHex"`
		SignatureBase64 string `json:"signatureBase64"`
	} `json:"cases"`
}

func loadVectors(t *testing.T) vectorFile {
	t.Helper()
	raw, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var v vectorFile
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(v.Cases) == 0 {
		t.Fatal("vectors file holds no cases")
	}
	return v
}

func walletFromHex(t *testing.T, hexKey string) sdkwallet.Interface {
	t.Helper()
	priv, err := ec.PrivateKeyFromHex(hexKey)
	if err != nil {
		t.Fatalf("parse key: %v", err)
	}
	w, err := sdkwallet.NewCompletedProtoWallet(priv)
	if err != nil {
		t.Fatalf("build wallet: %v", err)
	}
	return w
}

func TestCanonicalMatchesTypeScript(t *testing.T) {
	v := loadVectors(t)
	for _, c := range v.Cases {
		got := authproof.Canonical(c.Action, c.IdentityKey, c.ExpiresAt, c.Nonce)
		if hex.EncodeToString(got) != c.CanonicalHex {
			t.Errorf("%s: canonical bytes diverge from @bsv/auth\n got %s\nwant %s",
				c.Name, hex.EncodeToString(got), c.CanonicalHex)
		}
	}
}

func TestVerifyAcceptsTypeScriptSignatures(t *testing.T) {
	v := loadVectors(t)
	server := walletFromHex(t, v.ServerPrivHex)
	for _, c := range v.Cases {
		p := authproof.Proof{
			Action: c.Action, IdentityKey: c.IdentityKey,
			ExpiresAt: c.ExpiresAt, Nonce: c.Nonce, Signature: c.SignatureBase64,
		}
		now := time.UnixMilli(c.ExpiresAt).Add(-time.Minute)
		identity, err := authproof.Verify(context.Background(), server, p, c.Action, now)
		if err != nil {
			t.Errorf("%s: TS-signed proof refused: %v", c.Name, err)
			continue
		}
		if identity.ToDERHex() != v.ClientIdentityKey {
			t.Errorf("%s: authenticated wrong identity %s", c.Name, identity.ToDERHex())
		}
	}
}

func TestVerifyRefusesTampering(t *testing.T) {
	v := loadVectors(t)
	server := walletFromHex(t, v.ServerPrivHex)
	c := v.Cases[0]
	base := authproof.Proof{
		Action: c.Action, IdentityKey: c.IdentityKey,
		ExpiresAt: c.ExpiresAt, Nonce: c.Nonce, Signature: c.SignatureBase64,
	}
	now := time.UnixMilli(c.ExpiresAt).Add(-time.Minute)

	tampered := map[string]func(p authproof.Proof) (authproof.Proof, string){
		"action":    func(p authproof.Proof) (authproof.Proof, string) { p.Action += "x"; return p, p.Action },
		"expiry":    func(p authproof.Proof) (authproof.Proof, string) { p.ExpiresAt++; return p, p.Action },
		"nonce":     func(p authproof.Proof) (authproof.Proof, string) { p.Nonce = strings.Repeat("A", 44); return p, p.Action },
		"identity":  func(p authproof.Proof) (authproof.Proof, string) { p.IdentityKey = v.ServerIdentityKey; return p, p.Action },
		"signature": func(p authproof.Proof) (authproof.Proof, string) { p.Signature = v.Cases[1].SignatureBase64; return p, p.Action },
	}
	for name, mutate := range tampered {
		p, expected := mutate(base)
		if _, err := authproof.Verify(context.Background(), server, p, expected, now); err == nil {
			t.Errorf("tampered %s accepted", name)
		}
	}
}

func TestVerifyEnforcesFreshness(t *testing.T) {
	v := loadVectors(t)
	server := walletFromHex(t, v.ServerPrivHex)
	c := v.Cases[0]
	p := authproof.Proof{
		Action: c.Action, IdentityKey: c.IdentityKey,
		ExpiresAt: c.ExpiresAt, Nonce: c.Nonce, Signature: c.SignatureBase64,
	}

	if _, err := authproof.Verify(context.Background(), server, p, c.Action, time.UnixMilli(c.ExpiresAt)); err == nil {
		t.Error("proof accepted at its own expiry instant")
	}
	if _, err := authproof.Verify(context.Background(), server, p, c.Action, time.UnixMilli(c.ExpiresAt).Add(time.Hour)); err == nil {
		t.Error("expired proof accepted")
	}
	// A proof claiming to expire further out than window+skew allows is fabricated.
	tooEarly := time.UnixMilli(c.ExpiresAt).Add(-(authproof.Window + authproof.Skew + time.Second))
	if _, err := authproof.Verify(context.Background(), server, p, c.Action, tooEarly); err == nil {
		t.Error("proof with too-distant expiry accepted")
	}
}

func TestVerifyRefusesWrongAction(t *testing.T) {
	v := loadVectors(t)
	server := walletFromHex(t, v.ServerPrivHex)
	c := v.Cases[0]
	p := authproof.Proof{
		Action: c.Action, IdentityKey: c.IdentityKey,
		ExpiresAt: c.ExpiresAt, Nonce: c.Nonce, Signature: c.SignatureBase64,
	}
	now := time.UnixMilli(c.ExpiresAt).Add(-time.Minute)
	if _, err := authproof.Verify(context.Background(), server, p, "GET /v1/other", now); err == nil {
		t.Error("proof for a different action accepted")
	}
}

func TestSignRoundTripsThroughVerify(t *testing.T) {
	v := loadVectors(t)
	client := walletFromHex(t, v.ClientPrivHex)
	server := walletFromHex(t, v.ServerPrivHex)
	now := time.Now()

	action := authproof.Action("POST", "/v1/log/abc?seq=1&generation=1", strings.Repeat("ab", 32))
	p, err := authproof.Sign(context.Background(), client, v.ServerIdentityKey, action, now)
	if err != nil {
		t.Fatalf("sign: %v", err)
	}
	identity, err := authproof.Verify(context.Background(), server, p, action, now)
	if err != nil {
		t.Fatalf("verify own signature: %v", err)
	}
	if identity.ToDERHex() != v.ClientIdentityKey {
		t.Errorf("wrong identity %s", identity.ToDERHex())
	}
}

func TestHeaderEncodeDecode(t *testing.T) {
	p := authproof.Proof{Action: "GET /v1/manifest", IdentityKey: "02ab", ExpiresAt: 5, Nonce: "n", Signature: "s"}
	hv, err := authproof.Encode(p)
	if err != nil {
		t.Fatalf("encode: %v", err)
	}
	got, err := authproof.Decode(hv)
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	if got != p {
		t.Errorf("round trip changed the proof: %+v", got)
	}

	for _, bad := range []string{"", "!!!", "e30=" /* {} */, "bm90IGpzb24="} {
		if _, err := authproof.Decode(bad); err == nil {
			t.Errorf("decoded junk header %q", bad)
		}
	}
}

func TestActionShapes(t *testing.T) {
	if got := authproof.Action("GET", "/v1/manifest", ""); got != "GET /v1/manifest" {
		t.Errorf("bodyless action: %s", got)
	}
	withBody := authproof.Action("POST", "/v1/log/d?seq=1", "aa")
	if withBody != "POST /v1/log/d?seq=1 sha256=aa" {
		t.Errorf("body action: %s", withBody)
	}
	if got := authproof.BodySha256(withBody); got != "aa" {
		t.Errorf("extracted digest: %s", got)
	}
	if got := authproof.BodySha256("GET /v1/manifest"); got != "" {
		t.Errorf("bodyless digest should be empty, got %s", got)
	}
}
