// The proof tests pin the wire format against the published @bsv/auth verifier rather
// than against our own code: if verifyAuthProof accepts what signProofHeader produces,
// the Go server (whose vectors are generated by the same package) accepts it too.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { verifyAuthProof } from '@bsv/auth'
import { CompletedProtoWallet, PrivateKey, Utils } from '@bsv/sdk'
import { buildAction, signProofHeader, PROOF_WINDOW_MS, PROTOCOL } from '../dist/index.js'

const clientWallet = new CompletedProtoWallet(PrivateKey.fromHex('11'.repeat(32)))
const serverWallet = new CompletedProtoWallet(PrivateKey.fromHex('22'.repeat(32)))

async function identityKeyOf (wallet) {
  const { publicKey } = await wallet.getPublicKey({ identityKey: true })
  return publicKey
}

function decodeHeader (header) {
  return JSON.parse(Buffer.from(header, 'base64').toString('utf8'))
}

// Reassemble @bsv/auth's nested proof shape from our flat wire JSON.
function asAuthProof (wire) {
  return {
    data: {
      action: wire.action,
      identityKey: wire.identityKey,
      expiresAt: wire.expiresAt,
      nonce: wire.nonce
    },
    signature: Utils.toArray(wire.signature, 'base64')
  }
}

test('the header decodes to a proof that verifyAuthProof accepts for the exact action', async () => {
  const action = buildAction(
    'POST',
    '/v1/log/0123456789abcdef?seq=1&generation=1',
    '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae'
  )
  const header = await signProofHeader(clientWallet, await identityKeyOf(serverWallet), action)

  const wire = decodeHeader(header)
  const result = await verifyAuthProof({
    wallet: serverWallet,
    proof: asAuthProof(wire),
    action,
    protocol: PROTOCOL,
    consumeNonce: () => true
  })
  assert.equal(result.error, undefined)
  assert.equal(result.valid, true)
  assert.equal(result.identityKey, await identityKeyOf(clientWallet))
})

test('a proof minted for one request verifies for no other action', async () => {
  const action = buildAction('GET', '/v1/manifest')
  const header = await signProofHeader(clientWallet, await identityKeyOf(serverWallet), action)

  const result = await verifyAuthProof({
    wallet: serverWallet,
    proof: asAuthProof(decodeHeader(header)),
    action: buildAction('DELETE', '/v1/account'),
    protocol: PROTOCOL,
    consumeNonce: () => true
  })
  assert.equal(result.valid, false)
})

test('the wire proof carries the signed action verbatim and a 2 minute expiry', async () => {
  const now = 1755700000000
  const action = buildAction('GET', '/v1/log/dev?generation=3&from=7&limit=10')
  const header = await signProofHeader(clientWallet, await identityKeyOf(serverWallet), action, now)

  const wire = decodeHeader(header)
  assert.equal(wire.action, action)
  assert.equal(wire.expiresAt, now + PROOF_WINDOW_MS)
  assert.equal(wire.identityKey, await identityKeyOf(clientWallet))
  // 32 random bytes in base64; the server also uses it as the derivation keyID.
  assert.equal(Buffer.from(wire.nonce, 'base64').length, 32)
})
